-------------------------------------------------------------------------------
Test set: zenika.obs.api.failure.ObsRemoteFailureTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 1.476 s <<< FAILURE! - in zenika.obs.api.failure.ObsRemoteFailureTest
testStartRecordingFailure  Time elapsed: 1.384 s  <<< ERROR!
java.net.ConnectException: Connexion refusée (Connection refused)
	at zenika.obs.api.failure.ObsRemoteFailureTest.testStartRecordingFailure(ObsRemoteFailureTest.java:24)

testCloseConnectionEndpointFailure  Time elapsed: 0.038 s  <<< ERROR!
java.net.ConnectException: Connexion refusée (Connection refused)
	at zenika.obs.api.failure.ObsRemoteFailureTest.testCloseConnectionEndpointFailure(ObsRemoteFailureTest.java:42)

testOpenConnectionEndpointFailure  Time elapsed: 0.022 s  <<< ERROR!
java.net.ConnectException: Connexion refusée (Connection refused)
	at zenika.obs.api.failure.ObsRemoteFailureTest.testOpenConnectionEndpointFailure(ObsRemoteFailureTest.java:15)

testStopRecordingFailure  Time elapsed: 0.022 s  <<< ERROR!
java.net.ConnectException: Connexion refusée (Connection refused)
	at zenika.obs.api.failure.ObsRemoteFailureTest.testStopRecordingFailure(ObsRemoteFailureTest.java:33)

